CREATE TABLE IF NOT EXISTS lot_status (
    lot_id      VARCHAR(32) PRIMARY KEY,
    state       VARCHAR(16) NOT NULL,
    tool_id     VARCHAR(32),
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT
    ON *.* TO 'debezium'@'%';
FLUSH PRIVILEGES;

